name: flutter_weather_app
description: A new Flutter project

dependencies:
  flutter:
    sdk: flutter
  # Add your other dependencies here

dev_dependencies:
  flutter_lints: ^2.0.0  # Correctly indented

flutter:
  uses-material-design: true
